vex::brain Brain;
vex::motor BackLeft = vex::motor(vex::PORT2, vex::gearSetting::ratio18_1, false);
vex::motor FrontLeft = vex::motor(vex::PORT7, vex::gearSetting::ratio18_1);
vex::motor BackRight = vex::motor(vex::PORT1, vex::gearSetting::ratio18_1, true);
vex::motor FrontRight = vex::motor(vex::PORT8, vex::gearSetting::ratio18_1, true);
vex::motor Intake = vex::motor(vex::PORT6, vex::gearSetting::ratio36_1);
vex::motor Shooter = vex::motor(vex::PORT9, vex::gearSetting::ratio6_1, true);
vex::motor ShooterAux = vex::motor(vex::PORT10, vex::gearSetting::ratio6_1, false);
vex::limit Limit1 = vex::limit(Brain.ThreeWirePort.A);
vex::motor Flipper = vex::motor(vex::PORT11, vex::gearSetting::ratio18_1, true);
vex::controller Controller1 = vex::controller();
vex::competition Competition = vex::competition();
